version: '3'

services:
  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - webnet

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/kittipong.signalschool.co/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/kittipong.signalschool.co/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web1
      - web2
    networks:
      - webnet

networks:
  webnet:

